-- Migration: Auto-Exclusion Support
-- Run this in the Neon SQL Editor
-- Purpose: Add fields and table to support auto-exclusion tagging for compliance calls
-- This enables the system to automatically exclude calls from compliance calculations
-- based on configurable strategies (Peak Load, Weather, CAD Outage, etc.)

-- ============================================================================
-- 1. ADD AUTO-EXCLUSION COLUMNS TO CALLS TABLE
-- ============================================================================
-- These columns track whether a call was auto-excluded and why

-- Flag indicating the call was excluded by the auto-exclusion engine (not manually)
ALTER TABLE calls ADD COLUMN IF NOT EXISTS is_auto_excluded BOOLEAN DEFAULT FALSE;

-- The strategy key that triggered the auto-exclusion (e.g., 'PEAK_LOAD', 'WEATHER', 'CAD_OUTAGE')
ALTER TABLE calls ADD COLUMN IF NOT EXISTS auto_exclusion_strategy VARCHAR(50);

-- Human-readable reason generated by the auto-exclusion engine
ALTER TABLE calls ADD COLUMN IF NOT EXISTS auto_exclusion_reason TEXT;

-- Timestamp when the auto-exclusion decision was made
ALTER TABLE calls ADD COLUMN IF NOT EXISTS auto_excluded_at TIMESTAMPTZ;

-- JSON metadata from the engine (thresholds, scores, context used for the decision)
-- Supports legal defensibility and "plain-English explanation" generation
ALTER TABLE calls ADD COLUMN IF NOT EXISTS auto_exclusion_metadata JSONB;

-- ============================================================================
-- 2. CREATE EXCLUSION_LOGS TABLE FOR AUDIT TRAIL
-- ============================================================================
-- This table provides a complete audit trail of all exclusion decisions
-- (both auto and manual) for compliance reporting and legal defensibility

CREATE TABLE IF NOT EXISTS exclusion_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Link to the call being excluded
  call_id INTEGER NOT NULL,
  
  -- Exclusion type: 'AUTO' for engine-driven, 'MANUAL' for user-driven
  exclusion_type VARCHAR(10) NOT NULL CHECK (exclusion_type IN ('AUTO', 'MANUAL')),
  
  -- Strategy key for AUTO exclusions (PEAK_LOAD, WEATHER, CAD_OUTAGE, etc.)
  -- NULL for MANUAL exclusions
  strategy_key VARCHAR(50),
  
  -- Human-readable reason
  -- For AUTO: generated by engine (e.g., "Peak load detected: 5 calls in 10-minute window")
  -- For MANUAL: entered by user
  reason TEXT NOT NULL,
  
  -- User who made the exclusion decision
  -- NULL for AUTO exclusions (system-driven)
  created_by_user_id UUID,
  created_by_email VARCHAR(255),
  
  -- Engine metadata for AUTO exclusions (thresholds, scores, context)
  -- Enables reproducibility and plain-English explanation generation
  engine_metadata JSONB,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Soft delete support for reverting exclusions
  reverted_at TIMESTAMPTZ,
  reverted_by_user_id UUID,
  reverted_by_email VARCHAR(255),
  revert_reason TEXT
);

-- Index for efficient lookups by call
CREATE INDEX IF NOT EXISTS idx_exclusion_logs_call_id ON exclusion_logs(call_id);

-- Index for audit queries by type and date
CREATE INDEX IF NOT EXISTS idx_exclusion_logs_type_date ON exclusion_logs(exclusion_type, created_at);

-- Index for user activity audits
CREATE INDEX IF NOT EXISTS idx_exclusion_logs_user ON exclusion_logs(created_by_user_id);

-- ============================================================================
-- 3. CREATE AUTO_EXCLUSION_CONFIGS TABLE FOR STRATEGY SETTINGS
-- ============================================================================
-- Stores configurable thresholds and settings for each auto-exclusion strategy
-- per region, enabling region-specific tuning

CREATE TABLE IF NOT EXISTS auto_exclusion_configs (
  id SERIAL PRIMARY KEY,
  
  -- Region scope (NULL = global default)
  region_id INTEGER REFERENCES regions(id) ON DELETE CASCADE,
  
  -- Strategy key (PEAK_LOAD, WEATHER, CAD_OUTAGE, etc.)
  strategy_key VARCHAR(50) NOT NULL,
  
  -- Whether this strategy is enabled
  is_enabled BOOLEAN DEFAULT TRUE,
  
  -- Strategy-specific configuration as JSON
  -- e.g., { "call_threshold": 5, "time_window_minutes": 10 } for PEAK_LOAD
  config JSONB NOT NULL DEFAULT '{}',
  
  -- Audit fields
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by_user_id UUID,
  
  -- Ensure unique strategy per region (NULL region = global)
  UNIQUE(region_id, strategy_key)
);

-- ============================================================================
-- 4. INSERT DEFAULT STRATEGY CONFIGURATIONS
-- ============================================================================
-- These are global defaults; regions can override with their own settings

INSERT INTO auto_exclusion_configs (region_id, strategy_key, is_enabled, config)
VALUES 
  (NULL, 'PEAK_LOAD', FALSE, '{"call_threshold": 5, "time_window_minutes": 10, "description": "Multiple calls in same area within time window"}'),
  (NULL, 'WEATHER', FALSE, '{"severity_threshold": "severe", "description": "Severe weather events affecting response times"}'),
  (NULL, 'CAD_OUTAGE', FALSE, '{"description": "CAD system outages affecting dispatch accuracy"}')
ON CONFLICT (region_id, strategy_key) DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these to verify the migration was successful:

-- Check new columns on calls table
-- SELECT column_name, data_type FROM information_schema.columns 
-- WHERE table_name = 'calls' AND column_name LIKE '%auto%';

-- Check exclusion_logs table exists
-- SELECT COUNT(*) FROM exclusion_logs;

-- Check auto_exclusion_configs defaults
-- SELECT * FROM auto_exclusion_configs;

